defaultStake: 10000
defaultFee: 2000
borChainId: 15001
heimdallChainId: heimdall-15001
contractsRepo: https://github.com/0xPolygon/pos-contracts.git
contractsBranch: anvil-pos
genesisContractsRepo: https://github.com/0xPolygon/genesis-contracts.git
genesisContractsBranch: master
borRepo: https://github.com/shibaone/bor.git
borBranch: v2.0.4-bone-candidate
heimdallRepo: https://github.com/shibaone/heimdall.git
heimdallBranch: v1.2.3-bone-candidate
sprintSize:
- '64'
blockNumber:
- '0'
blockTime:
- '5'
numOfBorValidators: 3
numOfBorSentries: 0
numOfBorArchiveNodes: 0
numOfErigonValidators: 0
numOfErigonSentries: 0
numOfErigonArchiveNodes: 0
ethURL: http://anvil:9545
ethHostUser: ubuntu
devnetType: docker
borDockerBuildContext: "https://github.com/maticnetwork/bor.git#v2.0.4-bone-candidate"
heimdallDockerBuildContext: "../../heimdall"
sprintSizeBlockNumber:
- '0'
devnetBorFlags: config,config,config
mnemonic: 'clock radar mass judge dismiss just intact mind resemble fringe diary casino'
