name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
      # to be used by fork patch-releases ^^
      - 'v*.*.*-*'

env:
  ECR_REGION: us-east-1

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.20.x

      - name: Prepare
        id: prepare
        run: |
            TAG=${GITHUB_REF#refs/tags/}
            echo ::set-output name=tag_name::${TAG}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configure AWS Credentials
        if: success()
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_KEY_ID }}
            aws-region: ${{ env.ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Run GoReleaser
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.prepare.outputs.tag_name }}
          # SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          # DOCKER_USERNAME: ${{ secrets.DOCKERHUB }}
          # DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_KEY }}
